export const _500_TEMPLATE = [
  {
    key: '0',
    text: 'Копія топографічно-геодезичних матеріалів',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '1',
    text: 'з масштабу 1:500, наявних в управлінні',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '2',
    text: 'архітектури та урбаністики',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '3',
    text: 'за адресою: ',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '4',
    text: '',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '5',
    text: 'для інформації',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [
      {
        offset: 0,
        length: 14,
        style: 'BOLD',
      },
    ],
    entityRanges: [],
    data: {},
  },
];

export const _500_TEMPLATE_CAD = [
  {
    key: '0',
    text: 'Копія топографічно-геодезичних матеріалів',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '1',
    text: 'з масштабу 1:500, наявних в управлінні',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '2',
    text: 'архітектури та урбаністики',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '3',
    text: 'за адресою: ',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '4',
    text: 'кадастровий номер: ',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '5',
    text: '',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '6',
    text: 'для інформації',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [
      {
        offset: 0,
        length: 14,
        style: 'BOLD',
      },
    ],
    entityRanges: [],
    data: {},
  },
];

export const _2000_TEMPLATE = [
  {
    key: '0',
    text: 'Копія топографічно-геодезичних матеріалів',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '1',
    text: 'з масштабу 1:2000, наявних в управлінні',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '2',
    text: 'архітектури та урбаністики',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '3',
    text: 'за адресою: ',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '4',
    text: '',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [],
    entityRanges: [],
    data: {},
  },
  {
    key: '5',
    text: 'для інформації',
    type: 'unstyled',
    depth: 0,
    inlineStyleRanges: [
      {
        offset: 0,
        length: 14,
        style: 'BOLD',
      },
    ],
    entityRanges: [],
    data: {},
  },
];

export const TEMPLATE_OPTIONS = [
  { label: '500', value: _500_TEMPLATE },
  { label: '500_CAD', value: _500_TEMPLATE_CAD },
  { label: '2000', value: _2000_TEMPLATE },
];
